### ISSUE TITLE
【Bug 反馈】使用时EXCEL的复制和格式刷功能无效

### ISSUE THREAD

**Issue by pdwangchao** [RubberTranslator/RubberTranslator#4]
首先感谢作者提供的强力软件，这个是我目前用到的同类中最好的工具。
**bug描述**

3.5.0版本时，会导致EXCEL只能复制文字，会把复制的内容直接格式化，以及格式刷功能无效。
更新到3.5.1后，EXCEL的复制功能和格式刷功能直接失效了。
 倒也不是什么特别困扰的事，相比于增加的便利性来说，可以忍受。用到这两个功能时关一下RubberTranslator就好了。
**bug复现**

如何复现这个bug。
我的Office版本是Office365订阅版。

**平台与版本**

 - OS: Windows
 - Version: v3.5.1

**其他信息**

无

**Comment by pdwangchao** [comment]
更正一下，新版本的BUG还是复制内容格式化的问题，都是使用EXCEL，3.5.0版本时，复制后还有虚线框，但是格式已经丢失了。3.5.1版本直接虚线框也不出了，但是复制的内容还在剪切板，格式仍然是丢失的。所以改变的还是表象，实质的BUG两个版本是差不多的。

**Comment by ravenxrz** [comment]
这个rt的处理文本机制有关，只要识别到剪切板有内容，就会自动执行一些处理，建议把excel加入到过滤名单中。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月20日(周二) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [RubberTranslator/RubberTranslator] 【Bug 反馈】使用时EXCEL的复制和格式刷功能无效 (#4)




 
首先感谢作者提供的强力软件，这个是我目前用到的同类中最好的工具。
 bug描述
 
3.5.0版本时，会导致EXCEL只能复制文字，会把复制的内容直接格式化，以及格式刷功能无效。
 更新到3.5.1后，EXCEL的复制功能和格式刷功能直接失效了。
 倒也不是什么特别困扰的事，相比于增加的便利性来说，可以忍受。用到这两个功能时关一下RubberTranslator就好了。
 bug复现
 
如何复现这个bug。
 我的Office版本是Office365订阅版。
 
平台与版本
  
OS: Windows 

Version: v3.5.1 
 
其他信息
 
无
